const PDFDocument = require('pdfkit');
const { getDb } = require('../config/database');
const path = require('path');

const generateExamPDF = async (examId, schoolId) => {
  const db = getDb();

  const [exams] = await db.query(
    'SELECT e.*, s.name as subject_name, c.name as class_name, sc.name as school_name ' +
    'FROM exams e ' +
    'JOIN subjects s ON e.subject_id = s.id ' +
    'JOIN classes c ON e.class_id = c.id ' +
    'JOIN schools sc ON e.school_id = sc.id ' +
    'WHERE e.id = ? AND e.school_id = ?',
    [examId, schoolId]
  );

  if (exams.length === 0) {
    throw new Error('Exam not found');
  }

  const exam = exams[0];

  const [questions] = await db.query(
    'SELECT * FROM questions WHERE exam_id = ? ORDER BY question_number ASC',
    [examId]
  );

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const buffers = [];

    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => {
      const pdfData = Buffer.concat(buffers);
      resolve(pdfData);
    });
    doc.on('error', reject);

    // Header
    doc.fontSize(16).font('Helvetica-Bold').text(exam.school_name, { align: 'center' });
    doc.fontSize(14).font('Helvetica-Bold').text('EXAMINATION PAPER', { align: 'center' });
    doc.moveDown(0.5);

    doc.fontSize(12).font('Helvetica').text(`Subject: ${exam.subject_name}`, { align: 'center' });
    doc.fontSize(12).text(`Class: ${exam.class_name}`, { align: 'center' });
    doc.fontSize(12).text(`Exam Code: ${exam.exam_code}`, { align: 'center' });
    doc.fontSize(12).text(`Term: ${exam.term || 'N/A'} | Academic Year: ${exam.academic_year || 'N/A'}`, { align: 'center' });
    doc.moveDown(0.5);

    doc.fontSize(11).font('Helvetica-Bold').text(`Total Marks: ${exam.total_marks} | Duration: ${exam.duration_minutes || 'N/A'} minutes`, { align: 'center' });
    doc.fontSize(11).text(`Passing Marks: ${exam.passing_marks || 'N/A'}`, { align: 'center' });
    doc.moveDown(0.5);

    // Line separator
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.5);

    // Instructions
    if (exam.instructions) {
      doc.fontSize(11).font('Helvetica-Bold').text('INSTRUCTIONS:');
      doc.fontSize(10).font('Helvetica').text(exam.instructions);
      doc.moveDown(0.5);
    }

    // Student info fields
    doc.fontSize(11).font('Helvetica-Bold').text('Name: ________________________________    Date: ________________');
    doc.moveDown(0.5);

    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.5);

    // Questions
    questions.forEach((q, index) => {
      if (doc.y > 680) {
        doc.addPage();
      }

      doc.fontSize(11).font('Helvetica-Bold').text(`Question ${q.question_number} [${q.marks} mark${q.marks > 1 ? 's' : ''}]`);
      doc.fontSize(10).font('Helvetica').text(q.question_text);
      doc.moveDown(0.3);

      if (q.type === 'multiple_choice' && q.options) {
        try {
          const options = typeof q.options === 'string' ? JSON.parse(q.options) : q.options;
          const labels = ['A', 'B', 'C', 'D'];
          options.forEach((opt, i) => {
            doc.fontSize(10).font('Helvetica').text(`   ${labels[i]}. ${opt}`);
          });
        } catch (e) {
          doc.fontSize(10).font('Helvetica').text(q.options);
        }
      } else if (q.type === 'short_answer') {
        doc.moveDown(0.5);
        doc.fontSize(10).font('Helvetica').text('Answer:');
        doc.moveDown(0.3);
        // Draw lines for answer
        for (let i = 0; i < 4; i++) {
          doc.moveTo(70, doc.y).lineTo(530, doc.y).stroke();
          doc.moveDown(0.5);
          if (doc.y > 680) {
            doc.addPage();
          }
        }
      } else if (q.type === 'essay') {
        doc.moveDown(0.3);
        for (let i = 0; i < 8; i++) {
          doc.moveTo(70, doc.y).lineTo(530, doc.y).stroke();
          doc.moveDown(0.4);
          if (doc.y > 680) {
            doc.addPage();
          }
        }
      }

      doc.moveDown(0.5);
    });

    // Footer
    doc.moveDown(1);
    doc.fontSize(10).font('Helvetica').text('--- END OF EXAM ---', { align: 'center' });
    doc.fontSize(8).text(`Generated by Kosora App | ${new Date().toLocaleDateString()}`, { align: 'center' });

    doc.end();
  });
};

const generateOMRSheet = async (examId, schoolId) => {
  const db = getDb();

  const [exams] = await db.query(
    'SELECT e.*, s.name as subject_name, c.name as class_name, sc.name as school_name ' +
    'FROM exams e ' +
    'JOIN subjects s ON e.subject_id = s.id ' +
    'JOIN classes c ON e.class_id = c.id ' +
    'JOIN schools sc ON e.school_id = sc.id ' +
    'WHERE e.id = ? AND e.school_id = ?',
    [examId, schoolId]
  );

  if (exams.length === 0) {
    throw new Error('Exam not found');
  }

  const exam = exams[0];

  const [questions] = await db.query(
    'SELECT question_number FROM questions WHERE exam_id = ? AND type = "multiple_choice" ORDER BY question_number ASC',
    [examId]
  );

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    const buffers = [];

    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => {
      const pdfData = Buffer.concat(buffers);
      resolve(pdfData);
    });
    doc.on('error', reject);

    // Header
    doc.fontSize(14).font('Helvetica-Bold').text('OMR ANSWER SHEET', { align: 'center' });
    doc.fontSize(10).font('Helvetica').text(exam.school_name, { align: 'center' });
    doc.fontSize(10).text(`${exam.subject_name} - ${exam.class_name}`, { align: 'center' });
    doc.fontSize(10).text(`Exam Code: ${exam.exam_code}`, { align: 'center' });
    doc.moveDown(0.5);

    // Student info section
    doc.fontSize(10).font('Helvetica-Bold').text('Student Information:');
    doc.fontSize(10).font('Helvetica').text('Name: ________________________________    Student ID: ________________');
    doc.moveDown(0.3);
    doc.fontSize(10).text('Date: ________________    Signature: ________________');
    doc.moveDown(0.5);

    // Instructions
    doc.fontSize(9).font('Helvetica-Bold').text('Instructions:');
    doc.fontSize(8).font('Helvetica').text('1. Use a blue or black pen to fill in the circles completely.');
    doc.fontSize(8).text('2. Do not make any marks outside the circles.');
    doc.fontSize(8).text('3. If you need to change an answer, erase completely and fill in the new choice.');
    doc.fontSize(8).text('4. Each question has only ONE correct answer.');
    doc.moveDown(0.5);

    // Answer grid header
    doc.fontSize(9).font('Helvetica-Bold').text('Q.No.')
      .text('A', 75, doc.y, { width: 20 })
      .text('B', 95, doc.y, { width: 20 })
      .text('C', 115, doc.y, { width: 20 })
      .text('D', 135, doc.y, { width: 20 });
    doc.moveDown(0.2);

    // MCQ questions
    const mcqQuestions = questions.filter(q => q.question_number <= 50);

    mcqQuestions.forEach((q, index) => {
      if (index % 25 === 0 && index > 0) {
        doc.addPage();
        doc.fontSize(10).font('Helvetica-Bold').text('OMR ANSWER SHEET (continued)', { align: 'center' });
        doc.moveDown(0.5);
      }

      const xPos = 40;
      const labels = ['A', 'B', 'C', 'D'];

      // Question number
      doc.fontSize(9).font('Helvetica-Bold').text(String(q.question_number).padStart(2, '0'), xPos, doc.y, { width: 25 });

      // Bubbles
      labels.forEach((label, i) => {
        const cx = 75 + (i * 35);
        const cy = doc.y + 5;
        doc.circle(cx, cy, 6).stroke();
        doc.fontSize(7).font('Helvetica').text(label, cx - 3, cy + 8, { width: 6, align: 'center' });
      });

      doc.moveDown(0.6);

      if (doc.y > 700) {
        doc.addPage();
        doc.moveDown(0.5);
      }
    });

    // Footer
    doc.moveDown(1);
    doc.fontSize(8).font('Helvetica').text('--- This sheet will be scanned and graded automatically ---', { align: 'center' });
    doc.fontSize(7).text(`Generated by Kosora App | ${new Date().toLocaleDateString()}`, { align: 'center' });

    doc.end();
  });
};

module.exports = { generateExamPDF, generateOMRSheet };
